name: jdownloader
icon: snap/gui/icon.png
version: 2
summary: JDownloader
description: JDownloader is a free, open-source download management tool with a huge community of developers that makes downloading as easy and fast as it should be. Users can start, stop or pause downloads, set bandwith limitations, auto-extract archives and much more. It's an easy-to-extend framework that can save hours of your valuable time every day!
grade: stable
confinement: classic

apps:
  jdownloader:
    command: wrapper
    plugs: [home, shutdown, x11, network]

parts:
  jdownloader:
    plugin: dump
    source: dump-source
    prepare: |
      unlink usr/lib/jvm/java-8-openjdk-arm64/jre/lib/security/cacerts lint-snap-v2_external_symlinks
    after: [desktop-gtk3]
    stage-packages: [default-jre-headless, libc6]

#architectures: [amd64, i386, armhf]
