name: jdownloader
icon: snap/gui/icon.png
version: 2.0.1
summary: JDownloader
description: JDownloader is a free, open-source download management tool with a huge community of developers that makes downloading as easy and fast as it should be. Users can start, stop or pause downloads, set bandwith limitations, auto-extract archives and much more. It's an easy-to-extend framework that can save hours of your valuable time every day!
grade: stable
confinement: strict

apps:
  jdownloader:
    command: wrapper
    plugs: [home, shutdown, network, desktop, desktop-legacy, wayland, unity7]

parts:
  jdownloader:
    plugin: dump
    source: dump-source
    after: [desktop-gtk3]
    stage-packages: [default-jre-headless, libc6]

#architectures: [amd64, i386, armhf]
